name: calculatarr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Maven Project
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build WAR
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: calculator
          path: target/calculator.war

  deploy:
    name: Deploy to Tomcat
    runs-on: windows-latest
    needs: build
    environment: UAT

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v3
        with:
          name: calculator
          path: ./deploy

      - name: Cleanup remote Tomcat folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.UAT_IP }}
          port: ${{ vars.UAT_PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Cleaning Tomcat deployment folder..."
            rm -rf ${{ vars.UAT_TOMCAT }}/calculator*
      
      - name: Deploy WAR to Tomcat
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.UAT_IP }}
          port: ${{ vars.UAT_PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: './deploy/calculator.war'
          target: '${{ vars.UAT_TOMCAT }}/'

      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.UAT_IP }}
          port: ${{ vars.UAT_PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Listing deployed files..."
            ls -l ${{ vars.UAT_TOMCAT }}
