name: calculatarr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # --------------------------
  # CodeQL Analysis Job
  # --------------------------
  analyze:
    name: Analyze
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"

  # --------------------------
  # Build and Test Job
  # --------------------------
  build:
    name: Build & Test
    runs-on: windows-latest
    needs: analyze

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build & Test with Maven
        run: mvn clean verify

  # --------------------------
  # Cleanup Job
  # --------------------------
  cleanup:
    needs: [build]
    runs-on: windows-latest
    environment: UAT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cleanup destination folder on remote server
        shell: pwsh
        run: |
          # Create a temporary script for SSH
          $script = @"
          rm -rf ./deployment/*
          rm -rf $env:UAT_TOMCAT/digi*
          "@
          # Run SSH command
          ssh -i $env:SSH_KEY -p $env:UAT_PORT $env:USER@$env:UAT_IP $script
        env:
          UAT_IP: ${{ vars.UAT_IP }}
          UAT_PORT: ${{ vars.UAT_PORT }}
          USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          UAT_TOMCAT: ${{ vars.UAT_TOMCAT }}

  # --------------------------
  # Deploy Job
  # --------------------------
  deploy:
    needs: [cleanup]
    runs-on: windows-latest
    environment: UAT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: digibank.jar
          path: ./deploy

      - name: List downloaded artifact
        run: dir ./deploy

      - name: Copy artifact to remote server
        shell: pwsh
        run: |
          scp -i $env:SSH_KEY -P $env:UAT_PORT ./deploy/digibank.war $env:USER@$env:UAT_IP:deployment/
        env:
          UAT_IP: ${{ vars.UAT_IP }}
          UAT_PORT: ${{ vars.UAT_PORT }}
          USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
